In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("D:\\Downloads\\archive (1)\\ObesityDataSet_raw_and_data_sinthetic.csv")
df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [3]:
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [4]:
df.tail()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [5]:
df.sample(5)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
850,Male,21.620245,1.605314,66.621646,yes,yes,2.357496,3.376717,Sometimes,no,2.184843,no,1.358185,0.014885,Sometimes,Public_Transportation,Overweight_Level_I
677,Female,19.665881,1.676346,49.105025,no,no,2.720701,3.000000,Sometimes,no,2.000000,no,1.862235,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
1531,Male,23.260061,1.849003,121.414744,yes,yes,3.000000,2.595126,Sometimes,no,2.054072,no,0.835271,0.000000,Sometimes,Public_Transportation,Obesity_Type_II
136,Male,25.000000,1.790000,72.000000,yes,yes,2.000000,3.000000,Sometimes,no,2.000000,no,1.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
766,Male,21.017383,1.752391,79.109637,yes,yes,3.000000,1.000000,Sometimes,no,2.000000,no,2.572230,0.000000,Sometimes,Automobile,Overweight_Level_I

In [6]:
df.shape

(2111, 17)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [8]:
df.isna().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [9]:
cat_columns = df.columns[df.dtypes == 'object']
cat_columns

Index(['Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE',
       'SCC', 'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [10]:
num_columns = df.columns[df.dtypes != 'object']
num_columns

Index(['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE'], dtype='object')

In [11]:
for i in df[num_columns].columns:
    if i == 'Height':
        df[i] = df[i].round(2)
    elif i == 'Weight':
        df[i] == df[i].round(1)
    else:
        df[i] = df[i].astype('int32')

In [12]:
for i in df[cat_columns].columns:
    print(i)
    print("*********************************************************")
    print(set(df[i].tolist()))
    print("***************************************************************")

Gender
*********************************************************
{'Female', 'Male'}
***************************************************************
family_history_with_overweight
*********************************************************
{'no', 'yes'}
***************************************************************
FAVC
*********************************************************
{'no', 'yes'}
***************************************************************
CAEC
*********************************************************
{'Frequently', 'Sometimes', 'no', 'Always'}
***************************************************************
SMOKE
*********************************************************
{'no', 'yes'}
***************************************************************
SCC
*********************************************************
{'no', 'yes'}
***************************************************************
CALC
*********************************************************
{'Frequently', 'Sometimes', 'no', 'Always'}
***************************************************************
MTRANS
*********************************************************
{'Motorbike', 'Automobile', 'Public_Transportation', 'Walking', 'Bike'}
***************************************************************
NObeyesdad
*********************************************************
{'Overweight_Level_I', 'Normal_Weight', 'Obesity_Type_I', 'Insufficient_Weight', 'Overweight_Level_II', 'Obesity_Type_III', 'Obesity_Type_II'}
***************************************************************

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   int32
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   int32
 7   NCP                             2111 non-null   int32
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   int32
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   int32
 13  TUE                             2111 non-null   int32
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(2), int32(6), object(9)
memory usage: 231.0+ KB

In [14]:
from sklearn.preprocessing import LabelEncoder

def label_enc(df, cat_columns):
    encoder = LabelEncoder()
    for col in cat_columns:
        df[col] = encoder.fit_transform(df[col])

In [15]:
label_enc(df, cat_columns)

In [16]:
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21,1.62,64.0,1,0,2,3,2,0,2,0,0,1,3,3,1
1,0,21,1.52,56.0,1,0,3,3,2,1,3,1,3,0,2,3,1
2,1,23,1.80,77.0,1,0,2,3,2,0,2,0,2,1,1,3,1
3,1,27,1.80,87.0,0,0,3,3,2,0,2,0,2,0,1,4,5
4,1,22,1.78,89.8,0,0,2,1,2,0,2,0,0,0,2,3,6

In [17]:
X = df.drop('NObeyesdad', axis = 1)
y = df['NObeyesdad']

In [18]:
X.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,0,21,1.62,64.0,1,0,2,3,2,0,2,0,0,1,3,3
1,0,21,1.52,56.0,1,0,3,3,2,1,3,1,3,0,2,3
2,1,23,1.80,77.0,1,0,2,3,2,0,2,0,2,1,1,3
3,1,27,1.80,87.0,0,0,3,3,2,0,2,0,2,0,1,4
4,1,22,1.78,89.8,0,0,2,1,2,0,2,0,0,0,2,3

In [19]:
y.head()

0    1
1    1
2    1
3    5
4    6
Name: NObeyesdad, dtype: int32

In [20]:
from sklearn.model_selection import train_test_split

# Split Dataset into Training & Test Set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [21]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1688, 16), (423, 16), (1688,), (423,))

In [22]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [23]:
# Standard Scale Data
ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

# Tested MinMaxscaler as KNN Historicall Does Better with MinMax
mm = MinMaxScaler()
X_train_scaled_mm = mm.fit_transform(X_train_scaled)
X_test_scaled_mm = mm.transform(X_test_scaled)

def model_predict(X_train: pd.DataFrame, y_train: pd.DataFrame,X_test: pd.DataFrame, y_test: pd.DataFrame):
    models = [
        ('Random Forest', RandomForestClassifier()),
        ('Decision Tree', DecisionTreeClassifier()),
        ('KNN', KNeighborsClassifier()),
        ('SVM', SVC())
    ]

    for name, model in models:
        # Unscaled Data
        clf = model.fit(X_train, y_train)
        y_pred = clf.predict(X_test)

        # Scaled Data
        clf_scaled = model.fit(X_train_scaled, y_train)
        y_pred_scaled = clf_scaled.predict(X_test_scaled)

        # mm scaled Data
        clf_scaled_mm = model.fit(X_train_scaled_mm, y_train)
        y_pred_scaled_mm = clf_scaled_mm.predict(X_test_scaled_mm)

        # Accuracy Scores
        accuracy = round(accuracy_score(y_test, y_pred),5)
        scaled_acc = round(accuracy_score(y_test, y_pred_scaled),5)
        scaled_mm_acc = round(accuracy_score(y_test, y_pred_scaled_mm),5)

        # Output
        print(name + ':')
        print("************************************")
        print(f"Accuracy : {accuracy}")
        print(f"Accuracy w/Scaled Data(ss):{scaled_acc}")
        print(f"Accuracy w/Scaled Data(mm):{scaled_mm_acc}")
        if (accuracy > scaled_acc) and (accuracy > scaled_mm_acc):
            print(f"\nClassification Report:\n{classification_report(y_test, y_pred)}")
            print('***********************************************')
        elif (scaled_acc > scaled_mm_acc):
            print(f"\nClassification Report:\n{classification_report(y_test, y_pred_scaled_mm)}")
            print("********************************************")
        else:
            print(f"\nClassification Report\n:{classification_report(y_test, y_pred_scaled_mm)}")
            print("********************************************")

In [24]:
model_predict(X_train, y_train, X_test, y_test)

Random Forest:
************************************
Accuracy : 0.94326
Accuracy w/Scaled Data(ss):0.95035
Accuracy w/Scaled Data(mm):0.94799

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.96      0.96        56
           1       0.87      0.85      0.86        62
           2       0.99      0.96      0.97        78
           3       0.97      0.98      0.97        58
           4       1.00      1.00      1.00        63
           5       0.86      0.91      0.89        56
           6       1.00      0.96      0.98        50

    accuracy                           0.95       423
   macro avg       0.95      0.95      0.95       423
weighted avg       0.95      0.95      0.95       423

********************************************
Decision Tree:
************************************
Accuracy : 0.92199
Accuracy w/Scaled Data(ss):0.93381
Accuracy w/Scaled Data(mm):0.93381

Classification Report
:              precision    recall  f1-score   support

           0       0.91      0.95      0.93        56
           1       0.83      0.85      0.84        62
           2       0.97      0.94      0.95        78
           3       0.93      0.97      0.95        58
           4       1.00      1.00      1.00        63
           5       0.89      0.86      0.87        56
           6       1.00      0.98      0.99        50

    accuracy                           0.93       423
   macro avg       0.93      0.93      0.93       423
weighted avg       0.93      0.93      0.93       423

********************************************

AttributeError: 'Flags' object has no attribute 'c_contiguous'