In [127]:
import numpy as np
import pandas as pd

In [128]:
df = pd.read_csv("D:\\Downloads\\archive (1)\\ObesityDataSet_raw_and_data_sinthetic.csv")
df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [129]:
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [130]:
df.tail()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [131]:
df.sample(5)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
389,Female,16.000000,1.610000,65.000000,yes,yes,1.000000,1.000000,Sometimes,no,2.000000,no,0.000000,0.000000,no,Public_Transportation,Overweight_Level_I
861,Female,21.832995,1.580964,65.363941,no,yes,2.021446,3.000000,Sometimes,no,1.077917,no,0.523847,0.808599,Sometimes,Public_Transportation,Overweight_Level_I
684,Female,19.314429,1.672310,49.713944,no,yes,2.562409,3.488342,Sometimes,no,1.670620,no,2.000000,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
399,Male,21.000000,1.650000,60.000000,no,no,3.000000,1.000000,Frequently,no,1.000000,no,0.000000,0.000000,Sometimes,Motorbike,Normal_Weight
119,Female,19.000000,1.630000,76.000000,yes,no,3.000000,3.000000,Frequently,yes,3.000000,no,2.000000,1.000000,Sometimes,Automobile,Overweight_Level_II

In [132]:
df.shape

(2111, 17)

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [134]:
df.isna().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [135]:
cat_columns = df.columns[df.dtypes == 'object']
cat_columns

Index(['Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE',
       'SCC', 'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [136]:
num_columns = df.columns[df.dtypes != 'object']
num_columns

Index(['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE'], dtype='object')

In [137]:
for i in df[num_columns].columns:
    if i == 'Height':
        df[i] = df[i].round(2)
    elif i == 'Weight':
        df[i] == df[i].round(1)
    else:
        df[i] = df[i].astype('int32')

In [138]:
for i in df.columns:
    print(i)
    print("*********************************************************")
    print(set(df[i].tolist()))
    print("***************************************************************")

Gender
*********************************************************
{'Female', 'Male'}
***************************************************************
Age
*********************************************************
{14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 50, 51, 52, 55, 56, 61}
***************************************************************
Height
*********************************************************
{1.62, 1.78, 1.8, 1.52, 1.5, 1.64, 1.72, 1.85, 1.65, 1.77, 1.75, 1.58, 1.67, 1.83, 1.92, 1.93, 1.68, 1.76, 1.84, 1.59, 1.51, 1.69, 1.6, 1.94, 1.7, 1.53, 1.61, 1.86, 1.45, 1.95, 1.71, 1.79, 1.63, 1.88, 1.87, 1.54, 1.46, 1.55, 1.89, 1.56, 1.81, 1.73, 1.48, 1.9, 1.98, 1.66, 1.82, 1.57, 1.74, 1.91, 1.49}
***************************************************************
Weight
*********************************************************
{39.0, 40.0, 41.268597, 42.656563, 42.12617, 41.324558, 42.0, 42.3, 44.0, 45.0, 49.713944, 50.279053, 51.552595, 49.980968, 44.845655, 47.0, 48.0, 49.0, 50.0, 58.673963, 58.83071, 51.0, 52.0, 53.0, 54.5, 55.3, 56.0, 57.0, 59.0, 59.8, 60.0, 64.4, 66.5, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 79.849252, 80.037202, 80.986496, 82.144405, 74.0, 75.0, 85.743727, 81.0, 78.0, 88.096062, 88.079177, 82.0, 83.0, 84.0, 85.0, 85.5, 87.0, 88.0, 89.8, 90.0, 91.0, 93.0, 93.5, 95.0, 94.0, 96.0, 104.572712, 104.826776, 98.0, 99.0, 100.0, 102.0, 105.0, 107.0, 108.0, 109.0, 110.0, 112.0, 113.0, 114.0, 115.0, 120.209711, 121.684311, 121.458232, 118.0, 120.0, 121.0, 118.560509, 125.0, 126.67378, 121.657979, 130.0, 128.828122, 128.867444, 133.03441, 133.963349, 129.852531, 129.935666, 137.796884, 137.859737, 131.529267, 133.76473, 133.800129, 142.102468, 135.524857, 138.730619, 137.044959, 137.767787, 141.166265, 144.302261, 149.935848, 149.291106, 151.975864, 152.094362, 152.720545, 154.618446, 155.872093, 152.394739, 151.417292, 152.567671, 152.43563, 160.935351, 160.639405, 153.959945, 155.242672, 165.057269, 173.0, 41.397378, 42.367615, 43.365005, 44.641796, 44.050251, 44.762023, 49.742931, 50.631889, 51.5, 51.692272, 53.5, 55.0, 58.0, 58.5, 59.682591, 60.267427, 61.0, 62.0, 64.726948, 65.031879, 65.912688, 67.083121, 68.818893, 68.981403, 69.5, 70.0, 71.0, 71.602622, 71.728069, 71.799982, 72.0, 73.0, 73.91692, 74.959747, 74.885222, 75.093569, 76.0, 76.65949, 77.0, 77.74518, 77.272652, 77.561602, 77.550345, 78.55444, 78.88036, 77.033049, 77.098973, 78.233341, 79.0, 79.469513, 79.66832, 78.041338, 80.0, 80.386078, 80.005809, 80.420434, 80.413997, 80.400306, 82.228794, 82.853749, 82.283185, 82.52724, 82.967937, 83.986714, 83.390983, 83.986895, 83.285753, 84.75383, 84.315608, 84.416515, 84.729197, 84.897738, 85.803809, 85.302146, 85.637789, 85.073801, 85.255631, 85.196279, 86.0, 86.098523, 86.144904, 86.934846, 87.676154, 86.319887, 86.639861, 86.94538, 87.344156, 88.138777, 89.0, 89.652557, 89.558854, 89.994415, 89.868784, 89.991671, 91.499683, 91.363293, 92.0, 92.949254, 94.189167, 95.419668, 96.303855, 96.710735, 97.0, 97.185474, 98.790167, 98.699971, 98.296651, 99.430612, 99.540122, 100.5, 102.686239, 102.003378, 102.781971, 102.874549, 103.0344, 103.067766, 104.321463, 104.0, 104.954834, 104.988925, 104.839068, 105.448264, 105.712219, 105.655037, 105.042194, 105.037463, 105.428628, 105.359688, 107.482662, 108.9606, 108.934574, 108.316462, 109.758736, 109.980145, 110.400847, 110.818757, 111.235188, 111.942544, 111.267334, 111.856492, 111.894229, 112.089022, 112.835195, 112.395309, 112.776612, 111.949972, 114.133149, 114.187096, 114.254278, 115.39792, 115.382519, 116.311962, 117.57457, 117.8972, 117.631707, 119.117122, 119.373019, 120.082941, 85.137113, 120.613561, 120.794535, 120.775439, 121.658729, 120.699119, 120.021161, 120.158049, 121.864326, 104.936381, 125.973927, 126.088301, 127.161381, 127.427458, 128.856677, 129.232708, 129.991623, 129.232216, 129.874864, 129.349471, 130.927138, 129.769141, 130.871127, 129.466541, 131.274851, 131.929712, 132.8071, 132.116491, 132.262558, 133.365094, 133.952675, 133.783955, 133.843033, 133.886031, 133.45249, 133.478611, 133.870501, 135.346677, 137.852618, 137.858254, 137.785027, 46.655622, 46.062954, 150.51648, 150.37757, 49.895716, 50.165754, 51.457226, 51.881263, 153.149491, 55.01045, 59.990861, 111.9307, 84.493156, 111.922491, 39.695295, 41.706283, 42.848033, 42.3601, 44.188767, 49.650897, 52.629374, 61.616, 62.337721, 62.877347, 63.892071, 65.522744, 65.140408, 67.193585, 67.722222, 67.773914, 67.999778, 68.865008, 68.058902, 69.906708, 70.442775, 73.513873, 74.433362, 77.053948, 77.354744, 77.355417, 78.790936, 78.025625, 78.997166, 78.175706, 78.429312, 79.165306, 79.697278, 80.539, 80.615325, 82.27635, 82.954796, 82.851318, 82.193405, 82.470375, 83.121811, 82.919584, 83.199034, 83.337721, 82.039, 84.722222, 84.49798, 85.312639, 86.748295, 87.083266, 87.85785, 87.656029, 88.472359, 89.068227, 89.98168, 90.019501, 90.744965, 91.204753, 93.614246, 93.348843, 133.043941, 94.454394, 94.790579, 96.01851, 96.940255, 96.875502, 97.92035, 97.58826, 97.829344, 97.842406, 99.961731, 99.592225, 100.84763, 100.624553, 100.004418, 102.583895, 102.004554, 102.810704, 102.872802, 103.189532, 104.585783, 104.754958, 104.808542, 104.846817, 104.759643, 105.025808, 105.000276, 105.000097, 105.036075, 104.704707, 106.452367, 106.329569, 105.036522, 107.012256, 108.244379, 108.602715, 108.044313, 108.251044, 109.908779, 109.349025, 110.81746, 111.600553, 111.539494, 111.914361, 111.588625, 111.950113, 111.830924, 111.531208, 112.098616, 111.939983, 113.90198, 113.714521, 113.069667, 113.077187, 114.465425, 114.330023, 114.534678, 115.347176, 115.127662, 115.428276, 116.893105, 117.298233, 117.29188, 118.165082, 118.299585, 118.20313, 118.102897, 118.07381, 119.201465, 118.565568, 120.980508, 120.996581, 121.277832, 121.310257, 122.024954, 125.064264, 125.077863, 125.418548, 126.418413, 126.490236, 40.202773, 42.541794, 133.955091, 44.810751, 49.125955, 49.597765, 49.026214, 50.890363, 50.287967, 51.216463, 54.93242, 55.695253, 57.275946, 59.295172, 82.46376, 62.269912, 41.557468, 41.96525, 44.411801, 49.932199, 51.149283, 51.607091, 56.307019, 58.443049, 59.612717, 59.881316, 62.894283, 63.597633, 64.259379, 64.848627, 64.696248, 65.220249, 66.4, 67.140367, 68.77185, 69.975607, 69.242354, 69.936073, 71.927379, 72.467862, 73.193589, 73.939268, 75.5771, 75.951472, 75.306702, 75.399191, 75.0522, 76.129784, 77.956921, 77.858532, 78.300084, 78.434492, 78.008388, 78.156035, 78.089575, 79.713492, 79.989789, 79.843221, 80.993213, 81.919454, 81.66995, 81.022119, 81.281578, 82.523113, 82.130728, 82.459577, 82.582954, 82.603984, 83.1011, 83.785312, 82.249831, 84.687554, 84.451423, 85.720788, 85.301029, 86.963765, 86.464843, 86.963628, 87.105828, 87.107317, 88.965521, 88.600878, 88.126544, 89.496905, 89.836692, 89.424947, 90.52446, 90.500055, 91.798103, 93.086419, 93.798055, 93.890682, 95.285898, 96.568814, 97.971598, 98.259423, 99.982541, 100.642257, 101.544589, 101.285765, 102.950929, 102.523111, 102.093223, 102.784864, 102.134646, 102.320437, 104.928643, 104.774144, 104.791035, 104.854928, 104.772164, 104.879602, 105.037203, 106.49141, 106.038468, 106.69053, 107.55963, 107.378702, 108.395005, 108.829395, 108.10736, 109.195529, 109.411622, 110.714711, 110.676343, 110.777391, 110.621723, 111.169678, 111.93301, 111.868169, 111.95611, 111.939671, 112.875283, 112.010504, 112.277567, 112.10074, 112.173731, 113.15464, 113.277388, 113.372851, 114.004832, 114.511537, 114.480696, 115.531622, 115.025361, 115.45845, 116.669906, 117.86159, 118.277657, 118.548733, 118.805937, 119.484614, 119.956651, 120.8158, 120.202596, 104.807284, 121.835883, 121.204668, 121.786485, 121.82962, 121.094257, 121.244969, 121.560938, 121.421121, 128.261402, 128.114161, 128.148108, 129.679131, 129.157346, 129.19449, 131.76807, 131.335786, 132.145549, 132.94066, 133.665587, 133.937873, 133.878843, 133.618706, 133.903469, 133.676663, 133.845064, 133.742943, 133.689352, 133.346641, 137.832414, 138.202869, 138.143162, 140.292018, 41.535047, 111.036881, 49.869791, 49.699672, 50.664459, 152.217135, 152.473675, 51.965521, 56.029418, 58.325122, 59.895052, 61.10403, 63.856193, 42.993937, 42.069992, 42.096062, 133.10761, 43.087508, 44.581159, 44.376637, 44.316254, 49.660995, 49.603807, 49.105025, 50.869704, 50.157707, 51.7325, 51.491957, 53.8, 53.620604, 55.695036, 59.933015, 60.117993, 61.264785, 64.342459, 64.852953, 65.363941, 67.913561, 67.439589, 68.869791, 68.126955, 68.226511, 68.803694, 68.85097, 71.170001, 73.641633, 73.575981, 73.501233, 74.147443, 77.97917, 77.224574, 77.684229, 78.637307, 78.721696, 79.109029, 79.58958, 79.544998, 79.828725, 79.437921, 80.726195, 80.473587, 80.018571, 80.761409, 80.749657, 81.827288, 80.790813, 82.040318, 82.323954, 82.045045, 82.595793, 82.368441, 83.26312, 83.3258, 84.849349, 86.522799, 86.242679, 87.668828, 88.532032, 88.633616, 88.03748, 88.026943, 89.048151, 89.251639, 89.673648, 90.575934, 91.068054, 92.508122, 133.017105, 94.256547, 94.743892, 95.277392, 96.945262, 96.366777, 97.582959, 97.959899, 98.66176, 98.54302, 98.021766, 100.078367, 101.626189, 102.815983, 102.265955, 102.921218, 102.174953, 102.233445, 103.017623, 103.743534, 103.276087, 104.741914, 104.97003, 104.592372, 104.988082, 104.881994, 105.138073, 105.19936, 104.835346, 107.94747, 107.025415, 107.218949, 108.751502, 109.959714, 109.889334, 109.978402, 110.970479, 110.074946, 111.485516, 111.635463, 111.946655, 112.409191, 112.348722, 112.438508, 112.249699, 113.501549, 113.234349, 113.089716, 113.774198, 114.163921, 114.144378, 115.10813, 115.806977, 116.594351, 117.849351, 117.326523, 117.384745, 117.651046, 118.668332, 118.436166, 118.332689, 118.206565, 118.533246, 119.029103, 119.441207, 119.192922, 119.622764, 120.805715, 120.098812, 120.420406, 120.549592, 120.748213, 121.248035, 121.142535, 121.236915, 124.95278, 125.117633, 127.902844, 41.934368, 50.079991, 50.173425, 51.442293, 51.132809, 55.523481, 56.265959, 58.968994, 59.605028, 59.20945, 62.855073, 85.583485, 42.006282, 45.248627, 49.803921, 50.479039, 51.154201, 52.058335, 52.289828, 54.835576, 55.3707, 57.145917, 59.619485, 59.409018, 63.611109, 63.199726, 63.320629, 64.106108, 64.808022, 66.401407, 66.621646, 67.904023, 68.250249, 68.392133, 68.653347, 68.107866, 69.463458, 71.81338, 74.803157, 75.279605, 75.090439, 76.082517, 76.642944, 77.965532, 77.13322, 77.392179, 77.647716, 78.967919, 78.435904, 79.67793, 79.414603, 79.349221, 79.621463, 79.493626, 80.553067, 80.113493, 79.760922, 80.086524, 81.936398, 81.32297, 81.650778, 81.92991, 81.056851, 82.329047, 82.13682, 82.403076, 82.412665, 81.718232, 83.952968, 83.001642, 82.410189, 84.191125, 84.557797, 84.210535, 84.773349, 85.079589, 85.770013, 85.316125, 85.084364, 86.413388, 86.981202, 86.372141, 87.032398, 88.129437, 89.139209, 89.754302, 89.994351, 90.032671, 91.059595, 91.267087, 92.368359, 92.860254, 96.078462, 97.029249, 98.912261, 99.860254, 99.873716, 99.605527, 100.431625, 100.209405, 100.783434, 101.482054, 101.780099, 101.141277, 102.38745, 102.305767, 103.586342, 103.026858, 104.270062, 104.758713, 104.790549, 105.436173, 105.000789, 105.257543, 105.131956, 105.580491, 106.048516, 106.421042, 108.742005, 108.413119, 108.308112, 109.910012, 109.984263, 110.92217, 110.919646, 111.86899, 111.571076, 111.933152, 111.275646, 111.878132, 112.957922, 112.000381, 112.879662, 112.982549, 114.906095, 114.470482, 115.089316, 117.398976, 117.368716, 117.93329, 118.26569, 118.382361, 118.332966, 119.087557, 119.205308, 120.901591, 120.860386, 120.344402, 120.921535, 120.998266, 121.253083, 121.04172, 121.205171, 122.06261, 123.172214, 124.269251, 124.070717, 126.460936, 128.763843, 128.705761, 129.966428, 130.986338, 131.866734, 131.567481, 131.408528, 132.57927, 133.94608, 133.485478, 133.554686, 133.735889, 133.936535, 133.903612, 133.259033, 133.779919, 133.033523, 133.472641, 135.693381, 141.917802, 142.545183, 41.452385, 42.339767, 44.236067, 44.753943, 152.371911, 104.838425, 51.073918, 51.256059, 51.598593, 52.08657, 53.783977, 54.927529, 54.166453, 54.567343, 55.376512, 62.339003, 62.211572, 63.715219, 104.999403, 111.216192, 111.883747, 40.343463, 41.220175, 41.890204, 44.594588, 44.918255, 49.649613, 49.676046, 50.248677, 52.514302, 53.65727, 55.700497, 55.822119, 57.259124, 61.411141, 62.903938, 62.341438, 63.011645, 104.593929, 65.127324, 66.126964, 66.738769, 67.473282, 69.168978, 69.575315, 72.748903, 72.906186, 72.9518, 73.810728, 74.812707, 75.383716, 75.371244, 75.142858, 75.970712, 75.410647, 76.699774, 77.26813, 78.048207, 79.863546, 80.939733, 80.379575, 80.091886, 80.914382, 80.491339, 82.338464, 82.01831, 82.012637, 82.694689, 82.011962, 82.480214, 83.520113, 83.014033, 82.628, 82.528575, 84.134712, 84.783756, 85.607466, 85.687751, 87.861431, 88.675503, 89.429199, 89.993812, 91.052215, 94.094184, 95.032177, 95.952027, 95.324282, 96.192662, 97.813023, 98.44113, 99.544696, 100.245302, 100.066268, 100.941357, 102.872505, 102.083964, 102.277765, 103.771371, 103.393354, 104.548794, 104.40682, 104.821175, 104.986792, 104.947703, 105.055686, 105.000706, 105.479313, 105.028665, 105.031908, 106.875927, 105.313967, 105.407313, 107.998815, 107.10819, 108.204547, 108.019211, 108.15619, 108.265922, 109.900472, 109.599453, 109.982692, 109.996742, 110.21734, 110.803117, 110.10589, 110.168166, 111.208963, 111.829957, 111.919155, 111.841706, 111.945588, 112.471118, 112.536367, 112.740797, 112.200812, 111.157811, 113.90506, 112.555456, 114.77484, 116.160329, 116.157766, 117.75701, 118.237782, 118.424156, 119.434645, 120.423567, 120.60094, 120.009392, 120.975489, 85.228116, 121.065052, 121.414744, 120.898397, 121.471077, 120.988454, 127.507411, 111.357062, 43.919835, 47.124717, 49.804245, 50.088468, 50.951444, 51.588874, 52.331172, 52.09432, 54.121925, 54.997374, 55.879263, 55.967655, 104.810024, 111.00492, 104.92057, 44.661461, 49.039794, 49.838965, 49.839685, 49.945233, 51.437985, 51.710723, 54.98774, 57.790381, 58.913579, 59.313525, 59.243506, 60.628321, 62.631382, 64.814109, 68.06609, 68.016472, 69.743323, 75.480764, 75.62931, 75.057177, 75.688433, 76.126112, 77.929204, 77.431678, 77.601483, 78.997062, 78.030383, 79.752916, 79.278896, 80.273807, 80.535698, 80.311273, 80.135167, 81.108599, 82.207978, 82.586893, 82.414477, 82.532994, 83.414072, 83.314157, 83.15115, 83.282232, 84.064875, 84.340406, 85.050558, 85.568385, 86.565148, 86.002736, 86.0805, 87.070234, 87.27989, 89.802492, 89.998729, 89.667406, 89.995034, 89.738596, 90.924208, 90.13868, 91.630257, 93.638318, 93.429205, 93.310284, 95.887056, 95.361795, 97.416417, 97.911865, 98.572753, 99.812443, 99.530971, 99.199287, 99.709329, 100.543983, 101.038263, 102.59518, 102.000122, 102.555691, 103.605896, 103.669116, 104.899348, 104.846218, 104.966758, 104.768318, 104.94582, 105.966894, 105.696358, 105.254354, 105.686091, 105.055597, 106.320686, 105.000576, 105.423532, 105.122109, 105.013901, 108.721893, 108.800964, 108.897324, 109.207614, 110.79263, 110.545378, 110.008636, 110.804337, 110.640929, 111.950413, 111.993054, 111.818345, 110.930509, 111.884535, 112.007101, 112.932984, 112.289883, 112.287678, 112.226032, 113.207124, 113.215814, 113.451224, 114.097656, 114.067936, 115.627554, 116.974504, 117.468516, 117.792268, 118.183797, 118.154345, 118.740035, 118.114184, 118.377601, 119.081804, 120.702935, 120.751656, 120.996074, 120.919703, 121.527369, 121.889803, 122.333425, 123.721352, 124.704781, 124.805868, 127.642324, 129.013178, 129.363771, 111.863186, 131.902591, 131.877558, 131.042274, 132.527011, 132.904884, 132.054793, 133.573787, 133.852432, 133.466763, 133.888629, 133.281333, 133.166595, 134.842656, 133.662583, 133.644711, 133.747012, 136.516648, 137.79299, 138.034526, 39.850137, 39.371523, 141.799429, 142.559161, 41.669346, 147.296186, 49.815599, 49.98297, 49.558304, 151.278532, 50.92538, 51.107925, 51.121749, 54.98234, 62.871794, 62.417228, 111.720238, 85.002884, 39.101805, 41.952805, 43.534531, 44.00945, 50.424661, 51.524444, 53.699561, 54.877111, 55.003417, 58.854416, 58.943347, 58.19515, 111.682693, 61.373868, 63.183846, 65.423942, 65.062945, 65.293179, 67.183128, 67.939653, 68.908136, 69.529625, 69.3899, 71.788181, 72.105856, 72.713611, 74.244004, 75.150345, 75.948164, 75.920519, 75.828119, 75.816864, 76.202761, 77.426465, 77.205685, 77.473204, 77.00103, 78.073528, 78.370039, 78.664618, 78.055968, 78.574786, 79.079738, 79.661693, 79.109637, 80.555875, 80.458343, 80.993373, 80.351263, 81.384224, 81.918809, 81.978743, 82.085549, 82.636162, 83.568035, 83.016968, 85.833029, 85.261339, 87.272552, 87.906019, 87.286783, 87.803311, 88.119139, 88.431954, 89.93889, 89.28282, 89.909259, 89.393589, 90.671871, 90.004046, 91.495718, 92.69551, 95.290429, 95.564428, 95.269089, 96.738014, 97.350366, 97.449743, 98.182498, 98.447311, 98.490766, 98.579156, 99.623778, 99.083478, 99.204695, 100.618239, 100.176866, 101.634313, 101.067988, 102.592171, 102.022057, 102.910613, 102.363149, 102.686908, 103.841672, 103.706181, 103.175516, 103.250355, 103.705418, 104.303711, 104.578255, 104.187314, 103.180918, 104.950776, 105.800158, 105.496975, 105.619143, 104.954291, 106.509947, 106.042142, 106.528811, 108.012603, 108.090006, 109.931233, 110.824698, 110.074019, 111.886611, 111.999096, 111.927001, 111.946321, 111.821817, 112.323213, 112.725005, 112.256165, 111.555967, 113.235538, 114.479459, 114.482386, 115.828167, 116.164351, 116.102615, 117.708705, 118.370628, 118.40174, 118.134898, 118.363376, 119.841446, 119.050381, 120.431551, 120.337664, 120.872294, 120.151967, 120.644178, 121.737836, 120.399758, 120.589419, 121.284533, 121.639178, 122.137917, 122.119682, 122.609911, 122.813033, 126.798173, 49.928447, 49.516027, 50.833029, 51.314659, 55.511075, 58.585146, 58.621349, 59.258372, 63.65233}
***************************************************************
family_history_with_overweight
*********************************************************
{'yes', 'no'}
***************************************************************
FAVC
*********************************************************
{'yes', 'no'}
***************************************************************
FCVC
*********************************************************
{1, 2, 3}
***************************************************************
NCP
*********************************************************
{1, 2, 3, 4}
***************************************************************
CAEC
*********************************************************
{'no', 'Sometimes', 'Always', 'Frequently'}
***************************************************************
SMOKE
*********************************************************
{'yes', 'no'}
***************************************************************
CH2O
*********************************************************
{1, 2, 3}
***************************************************************
SCC
*********************************************************
{'yes', 'no'}
***************************************************************
FAF
*********************************************************
{0, 1, 2, 3}
***************************************************************
TUE
*********************************************************
{0, 1, 2}
***************************************************************
CALC
*********************************************************
{'Always', 'no', 'Frequently', 'Sometimes'}
***************************************************************
MTRANS
*********************************************************
{'Walking', 'Bike', 'Motorbike', 'Automobile', 'Public_Transportation'}
***************************************************************
NObeyesdad
*********************************************************
{'Insufficient_Weight', 'Obesity_Type_I', 'Overweight_Level_I', 'Normal_Weight', 'Overweight_Level_II', 'Obesity_Type_II', 'Obesity_Type_III'}
***************************************************************

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   int32
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   int32
 7   NCP                             2111 non-null   int32
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   int32
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   int32
 13  TUE                             2111 non-null   int32
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(2), int32(6), object(9)
memory usage: 231.0+ KB

In [140]:
from sklearn.preprocessing import LabelEncoder

def label_enc(df, cat_columns):
    encoder = LabelEncoder()
    for col in cat_columns:
        df[col] = encoder.fit_transform(df[col])

In [141]:
label_enc(df, cat_columns)

In [142]:
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21,1.62,64.0,1,0,2,3,2,0,2,0,0,1,3,3,1
1,0,21,1.52,56.0,1,0,3,3,2,1,3,1,3,0,2,3,1
2,1,23,1.80,77.0,1,0,2,3,2,0,2,0,2,1,1,3,1
3,1,27,1.80,87.0,0,0,3,3,2,0,2,0,2,0,1,4,5
4,1,22,1.78,89.8,0,0,2,1,2,0,2,0,0,0,2,3,6

In [143]:
X = df.drop('NObeyesdad', axis = 1)
y = df['NObeyesdad']

In [144]:
X.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,0,21,1.62,64.0,1,0,2,3,2,0,2,0,0,1,3,3
1,0,21,1.52,56.0,1,0,3,3,2,1,3,1,3,0,2,3
2,1,23,1.80,77.0,1,0,2,3,2,0,2,0,2,1,1,3
3,1,27,1.80,87.0,0,0,3,3,2,0,2,0,2,0,1,4
4,1,22,1.78,89.8,0,0,2,1,2,0,2,0,0,0,2,3

In [145]:
y.head()

0    1
1    1
2    1
3    5
4    6
Name: NObeyesdad, dtype: int32

In [146]:
from sklearn.model_selection import train_test_split

# Split Dataset into Training & Test Set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [147]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1688, 16), (423, 16), (1688,), (423,))

In [148]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [149]:
# Standard Scale Data
ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

# Tested MinMaxscaler as KNN Historicall Does Better with MinMax
mm = MinMaxScaler()
X_train_scaled_mm = mm.fit_transform(X_train_scaled)
X_test_scaled_mm = mm.transform(X_test_scaled)

def model_predict(X_train: pd.DataFrame, y_train: pd.DataFrame,X_test: pd.DataFrame, y_test: pd.DataFrame):
    models = [
        ('Random Forest', RandomForestClassifier()),
        ('Decision Tree', DecisionTreeClassifier()),
        ('KNN', KNeighborsClassifier()),
        ('SVM', SVC())
    ]

    for name, model in models:
        # Unscaled Data
        clf = model.fit(X_train, y_train)
        y_pred = clf.predict(X_test)

        # Scaled Data
        clf_scaled = model.fit(X_train_scaled, y_train)
        y_pred_scaled = clf_scaled.predict(X_test_scaled)

        # mm scaled Data
        clf_scaled_mm = model.fit(X_train_scaled_mm, y_train)
        y_pred_scaled_mm = clf_scaled_mm.predict(X_test_scaled_mm)

        # Accuracy Scores
        accuracy = round(accuracy_score(y_test, y_pred),5)
        scaled_acc = round(accuracy_score(y_test, y_pred_scaled),5)
        scaled_mm_acc = round(accuracy_score(y_test, y_pred_scaled_mm),5)

        # Output
        print(name + ':')
        print("************************************")
        print(f"Accuracy : {accuracy}")
        print(f"Accuracy w/Scaled Data(ss):{scaled_acc}")
        print(f"Accuracy w/Scaled Data(mm):{scaled_mm_acc}")
        if (accuracy > scaled_acc) and (accuracy > scaled_mm_acc):
            print(f"\nClassification Report:\n{classification_report(y_test, y_pred)}")
            print('***********************************************')
        elif (scaled_acc > scaled_mm_acc):
            print(f"\nClassification Report:\n{classification_report(y_test, y_pred_scaled_mm)}")
            print("********************************************")
        else:
            print(f"\nClassification Report\n:{classification_report(y_test, y_pred_scaled_mm)}")
            print("********************************************")

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   int32
 1   Age                             2111 non-null   int32
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   int32
 5   FAVC                            2111 non-null   int32
 6   FCVC                            2111 non-null   int32
 7   NCP                             2111 non-null   int32
 8   CAEC                            2111 non-null   int32
 9   SMOKE                           2111 non-null   int32
 10  CH2O                            2111 non-null   int32
 11  SCC                             2111 non-null   int32
 12  FAF                             2111 non-null   int32
 13  TUE                             2111 non-null   int32
 14  CALC                            2111 non-null   int32
 15  MTRANS                          2111 non-null   int32
 16  NObeyesdad                      2111 non-null   int32
dtypes: float64(2), int32(15)
memory usage: 156.8 KB

In [151]:
model_predict(X_train, y_train, X_test, y_test)

Random Forest:
************************************
Accuracy : 0.9409
Accuracy w/Scaled Data(ss):0.94326
Accuracy w/Scaled Data(mm):0.93853

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.96      0.96        56
           1       0.87      0.84      0.85        62
           2       0.97      0.96      0.97        78
           3       0.98      0.97      0.97        58
           4       1.00      1.00      1.00        63
           5       0.84      0.88      0.86        56
           6       0.92      0.96      0.94        50

    accuracy                           0.94       423
   macro avg       0.94      0.94      0.94       423
weighted avg       0.94      0.94      0.94       423

********************************************
Decision Tree:
************************************
Accuracy : 0.92435
Accuracy w/Scaled Data(ss):0.92435
Accuracy w/Scaled Data(mm):0.92908

Classification Report
:              precision    recall  f1-score   support

           0       0.91      0.95      0.93        56
           1       0.82      0.85      0.83        62
           2       0.96      0.94      0.95        78
           3       0.93      0.97      0.95        58
           4       1.00      1.00      1.00        63
           5       0.89      0.84      0.86        56
           6       1.00      0.96      0.98        50

    accuracy                           0.93       423
   macro avg       0.93      0.93      0.93       423
weighted avg       0.93      0.93      0.93       423

********************************************

AttributeError: 'Flags' object has no attribute 'c_contiguous'